### ISSUE TITLE
wrong required package while using composer installation way

### ISSUE THREAD

**Issue by sanaeefar-saeed** [magepow/magento-2-configurable-preselect#2]
Hi Team,

in composer.json this module requires magepow/community package
  "require": {
    "magepow/community": "^1.0.0"
  },

but in magepow/community all info refer to the (magepow/code|Magepow_Core) module except registration.php that is Magepow_Community

here is the error i'm getting :
{"0":"Module 'Magepow_Core' is not correctly registered.","1":"#1 Magento\\Framework\\Module\\Dir\\ReverseResolver->getModuleName()

so seems either require section should be core or magepow/community should be refactored or even it can be remove from required section since i couldn't find any dependency to it for this extension

**Comment by magiccart** [comment]
I have fix it, please check again.

**Comment by sanaeefar-saeed** [comment]
i can confirm that this issue has been fixed now. we can close this issue
Thanks @magiccart
